### ISSUE TITLE
Missing description in docs

### ISSUE THREAD

**Issue by Peterr-K** [synzen/MonitoRSS#183]
Hi

sorry if it's bad reporting here, anyway here
https://github.com/synzen/MonitoRSS/wiki/Configuration#database
is missing explanation for 'redis' what is part od Database group.

thanks

**Comment by jannyba** [comment]
sorrý the missing redis desc is also on your web site https://docs.monitorss.xyz/configuration/bot-configuration#database

**Comment by synzen** [comment]
I believe I see where you're getting "redis" from - in the `config.bot.example.json`. That is an outdated config, and is now removed. Thanks for the report.

**Comment by jannyba** [comment]
ok great, thanks for your work! :)
