### ISSUE TITLE
Feature Request: Feed Management by Groups

### ISSUE THREAD

**Issue by awowa** [synzen/MonitoRSS#187]
**Is your feature request related to a problem? Please describe.**

When wanting to replace a feed or manage a group of feeds, it becomes hard to go through the list of feeds to pinpoint which ones I am wanting to take out or replace with others at times. This occurs because the feed sources I use are only useful for a specific length of time, after which some feeds I no longer care about as others take more importance.

**Describe the solution you'd like**
I think being able to sort or bucket the feeds by a tag or descriptor, in essence assigning them to topic groups would be useful in managing the feed. As a user adds more feeds to the feed list, he may need a easier way to sort through the feeds when editing/removing/replacing some feeds with others. I believe this would be a nice QOL improvement for those with larger feed numbers, since it is hard to sometimes track which feeds go to which channels and which feeds need to be pruned or replaced when trying to edit some of the feeds on the feed list.

**Comment by synzen** [comment]
Thanks for the suggestion and the description of the problem. Are you sure that the `list` command doesn't solve this particular problem? You're able to filter by channel and/or by a search query as arguments to the list command, added in response to #168 . For more information on this, you can check out https://docs.monitorss.xyz/configuration/discord-commands.

You can also re-title the feeds (not with the bot unfortunately, only with the control panel) like so:

"Group1: Site A"
"Group1: Site B"
"Group2: Site C"

which can then allow you to filter by groups via search queries with the `list` command

**Comment by awowa** [comment]
Yes; actually that command helps a bunch. Thank you!

**Comment by synzen** [comment]
Glad to hear.
