### ISSUE TITLE
invited the bot , cant find default prefix

### ISSUE THREAD

**Issue by neofutur** [synzen/MonitoRSS#189]
**Describe the issue**
Hi , I invited the bot into my server to try it .
used the Bot Invite link from the readme : 
https://discord.com/oauth2/authorize?client_id=268478587651358721&scope=bot&permissions=19456

, he joined but I found no doc telling me the default prefix it uses, had a look at the code bu t I couldnt find the default prefix, seems to be some kind of environment variable .

**To Reproduce**
1. invite the bot to your server
2. try to find the default prefix to talk to him, he wont answer to rsshelp or ! rsshelp . . . 

**Expected behavior**
please tell in the docs what the default prefix is, after inviting the bot to my server, so i can talk to him :)

**Screenshots**

**Branch (please specify one):**
master or dev

If referencing the public bot, then specify public bot.

**Additional context**

**Comment by synzen** [comment]
Hi, thanks for the issue - I replied in the Discord server but I can reply here as well for visibility. You may find the default prefix on the Discord Commands page of the documentation (https://docs.monitorss.xyz/configuration/discord-commands)
![image](https://user-images.githubusercontent.com/18688793/94879459-43f3f400-042e-11eb-9941-045cfab7a4ee.png)
which is `rss.`
