### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by BonKerzHD** [synzen/MonitoRSS#191]
**Describe the bug**
Hi, I have encountered an Application Error after finishing the installation of the MonitoRSS with Heroku and I was asked to run the following CLI Command: 

heroku logs --tail

but this failed and gave me the following error:

heroku logs --tail
 ›   Error: Missing required flag:
 ›     -a, --app APP  app to run command against
 ›   See more help with --help

Is there anyone who can help me understand where I could have gone wrong. My Discord username is: BonKerzHD#4828

![Screen Shot 2020-11-26 at 06 48 47](https://user-images.githubusercontent.com/75057929/100317348-1c478500-2fb4-11eb-96cc-f55c4e393a1c.png)

**Comment by synzen** [comment]
Hi, apologies for the late reply.

Your command is missing a required flag - the error is telling you that you're missing the `-a` or `-app` argument to `heroku logs`.

Regardless however, this repo is only for the bot and has no web interface. For questions on deployments, please redirect such issues to https://github.com/synzen/MonitoRSS-Clone.
