### ISSUE TITLE
Allow users without 'manage channel perm' to use more commands

### ISSUE THREAD

**Issue by StrangeRanger** [synzen/MonitoRSS#193]
**Is your feature request related to a problem? Please describe.**
I've run into the issue a few times where users on my server want to list the feed the bot currently monitors. But due to permission errors, they can't use that command.

**Describe the solution you'd like**
It'd be nice if the commands not used to manage the bot or obviously should only be used by admins, were usable by regular users who don't have the manage channel perms

**Comment by synzen** [comment]
Thanks for following the template, and the suggestion. This is pretty complex at this time to support so I can't say that it'll be planned, but I will leave this issue opened in case it's ever revisited

**Comment by synzen** [comment]
This is no longer relevant with the advent of personal feeds/migration off of Discord commands
