### ISSUE TITLE
Listing unhealthy feeds

### ISSUE THREAD

**Issue by StrangeRanger** [synzen/MonitoRSS#194]
**Is your feature request related to a problem? Please describe.**
There are times where I'm told that there are unhealthy feeds or that there are feeds that have failed. There is no easy way of listing the feeds whose health is below 100%, so I have to use `rss.list` and scroll through everything to find the feeds with health less than 100%.

**Describe the solution you'd like**
It's would be nice if a command was created to list these unhealthy feeds. Or even a flag for the list command such as `rss.list unhealthy` OR `rss.list health [percentage]` (where it'd grab feeds with health less than or equal to the given percentage.

**Comment by synzen** [comment]
Thanks for the suggestion. I'll look into implementing this after the public bot has successfully moved off of Patreon.

**Comment by synzen** [comment]
This should now be implemented with personal feeds on the control panel.
