### ISSUE TITLE
(Self-hosted) bot is not resilient to intermittent connectivity issues

### ISSUE THREAD

**Issue by rzumer** [synzen/MonitoRSS#197]
**Describe the bug**
The bot stops working (responding to commands, etc.) after experiencing a temporary connectivity issue.

**To Reproduce**
Saturate the line or disconnect the machine where the bot is hosted for a few minutes.

**Expected behavior**
The bot reconnects gracefully once connectivity is restored.

**Actual behavior**
The bot needs to be restarted manually in order to respond to commands, update feeds, etc., even after connectivity has been restored for a significant amount of time

**Branch (please specify one):**
master

**Additional context**
In my case my line was saturated by an aggressive P2P client and I assume the bot timed out while trying to connect.

I do not have the log output anymore, but will add if I can reproduce again.

I saw that connection errors to the database are handled gracefully and so are timeouts to individual feeds. I don't know if this is caused by repeated connection issues or if there is another component that cannot handle failure.

**Comment by synzen** [comment]
Unfortunately I cannot reproduce your results. I disabled the network for several minutes with a remotely-connected MongoDB and it was still able to reconnect gracefully:

![image](https://user-images.githubusercontent.com/18688793/103249122-bf851480-493b-11eb-8ce2-d5518a168f3c.png)

**Comment by rzumer** [comment]
I also can't reproduce it, so it might be a general stability issue like the cases mentioned in #196. Closing unless I can reproduce again.
