### ISSUE TITLE
Add option to edit feed url

### ISSUE THREAD

**Issue by Rick-HM** [synzen/MonitoRSS#199]
I am constantly updating the link of a feed, and since there is no option to edit, I have to remove the link, add the new one and edit the message template again.
The feature of being able to edit the links would help a lot.

### **Concept:**

![Captura de pantalla 2021-01-25 203816](https://user-images.githubusercontent.com/61259627/105780749-e856f480-5f4f-11eb-8978-7b129719d937.png)
-------------

_Sorry if there is already an option to do this and I am not seeing it_

**Comment by synzen** [comment]
Thanks for the suggestion, I've added it https://github.com/synzen/MonitoRSS/projects/8

For the time being however, you can `rss.add` the new feed, `rss.clone` the settings from the old one, and then delete the old one. This way, you don't have to set the template again

**Comment by synzen** [comment]
This should now be possible with personal feeds on the [public bot](https://discord.com/oauth2/authorize?client_id=268478587651358721&scope=bot&permissions=19456). Personal feeds are still undocumented however, but with regard to this particular feature, it should be completed.
