### ISSUE TITLE
Bot sends only about 20 lines of RSS 

### ISSUE THREAD

**Issue by krzys1u** [synzen/MonitoRSS#201]
**Describe the bug**
I've added bot to my server, then i added http://feeds.feedburner.com/unknowNews rss and when new entry in rss was added bot sends only first 20 lines instead of full article

**Expected behavior**
Whole article is sent to Discord channel

**Screenshots**
<img width="1117" alt="Zrzut ekranu 2021-02-26 o 12 48 27" src="https://user-images.githubusercontent.com/12277541/109296657-fb036880-7830-11eb-89ec-68d8351b2fe6.png">

**Branch (please specify one):**
 public bot

**Additional context**

**Comment by synzen** [comment]
By default, content is truncated to try to fit everything in one message - if you enable splitting options via the `rss.split` command, it should show the full message and spit them into multiple messages if necessary

**Comment by krzys1u** [comment]
@synzen how can i do it?

**Comment by synzen** [comment]
You may use the `rss.split` command
