### ISSUE TITLE
[BUG] Empty Message 

### ISSUE THREAD

**Issue by BlackYuzia** [synzen/MonitoRSS#202]
**Describe the bug**
RSS Feed can't be sended with empty message. 

**To Reproduce**
1. Replace all content in text block by `{subscriptions}` tag.
2. Use Embeds
3. Get message about `can't send empy message`.

**Expected behavior**
Message should **send** without any errors. If `{subscriptions}` tag is empty, we should replace this tag by `{empty}` and/or add invisible symbols (like space (`" "`) or etc)

**Screenshots**
![image](https://user-images.githubusercontent.com/25010528/111202968-23c78400-85cd-11eb-8038-a2d0208d0816.png)
![image](https://user-images.githubusercontent.com/25010528/111203016-2aee9200-85cd-11eb-971c-b6380fe2f419.png)

**Branch:**
**public bot**

**Comment by synzen** [comment]
Apologies for the late reply, but I'm unable to reproduce this issue. Can you provide your `rss.backup` file/details? I need

1. The feed URL
2. Your exact text settings
3. Your exact embed settings

As they appear within the backup file.

**Comment by BlackYuzia** [comment]
Lol, idk what happen, but bot got crazy? :eyes:
![image](https://user-images.githubusercontent.com/25010528/113171842-8cab2f00-9250-11eb-80ca-eb9ecffc3487.png)
Anyway, he success add rss link... so, nvm?

```json
{
  "profile": null,
  "feeds": [
    {
      "filters": {},
      "rfilters": {},
      "title": "eM Client Secured Mail Client With Calendar",
      "url": "http://www.emclient.com/feed",
      "guild": "716194991575400469",
      "channel": "716194991575400472",
      "text": "{subscriptions}",
      "embeds": [],
      "addedAt": "2021-03-31T15:42:31.896Z",
      "ncomparisons": [],
      "pcomparisons": [],
      "regexOps": {},
      "_id": "60649867598fde32c212edd8"
    }
  ],
  "filteredFormats": [],
  "subscribers": []
}
```

Now, I try again, and get what if `embed` is exist, message would send success.
Anyway, if only `{subscriptions}` in main message block, I get error like:
```
Unable to send empty message for feed article https://www.emclient.com/blogpost.aspx?id=428 (60649867598fde32c212edd8).
```

**Comment by BlackYuzia** [comment]
@synzen fixed?
