### ISSUE TITLE
Question: How often is the feed checked?

### ISSUE THREAD

**Issue by jorijnsmit** [synzen/MonitoRSS#204]
I.e., what is the expected delay between publication of the article on the feed and the notification on Discord?

If you could point me to the source that is responsible for this that would be even better :-)

**Comment by jorijnsmit** [comment]
https://github.com/synzen/MonitoRSS/blob/2ac841ef6c246b2cc99965b9e87743f2c39b3199/src/commands/prompts/list/listFeeds.js#L180

Think I found it... Could this variable technically be set to check a feed every second?

**Comment by synzen** [comment]
Hi, this is determined by what you set in the config. All documentation for the bot is located at https://docs.monitorss.xyz/configuration/bot-configuration

**Comment by MorningSleeper** [comment]
@synzen just out of curiosity, what is the same setting set to for those using the publically hosted version of the bot since I assume it is not customizable to those using it that way?

**Comment by synzen** [comment]
> 
> 
> @synzen just out of curiosity, what is the same setting set to for those using the publically hosted version of the bot since I assume it is not customizable to those using it that way?

Apologies for the late reply. It is 10 minutes - you may check this by using the `rss.list` command.
