### ISSUE TITLE
[BUG] [WEB] Save Override Main Message Block

### ISSUE THREAD

**Issue by BlackYuzia** [synzen/MonitoRSS#205]
### Description 

When we use web (site) panel for edit and save `embed message block`, we can we can reset `main message block` if we edit and didn't save `main message block` before save `embed message block`.

### Steps to reproduce

1. Edit main message block
![image](https://user-images.githubusercontent.com/25010528/111868595-88932d80-8983-11eb-9c85-b2e664eb9887.png)
2. Edit embed message block (any component like `author` or etc)
3. Save embed.
![image](https://user-images.githubusercontent.com/25010528/111868614-9cd72a80-8983-11eb-8bc0-ae139f0a4c08.png)
4. Success! Main message block would reset to prev (before edit) result.
![image](https://user-images.githubusercontent.com/25010528/111868617-a5c7fc00-8983-11eb-8e87-8fc3420a2743.png)

Note: If you save main message block, embed block (or any component) wouldn't be reset.

#### Main Message Block 
![image](https://user-images.githubusercontent.com/25010528/111868550-44a02880-8983-11eb-9b50-cd72b75f0d40.png)

#### Embed Message Block
![image](https://user-images.githubusercontent.com/25010528/111868558-51bd1780-8983-11eb-8451-759e363e9ba0.png)

**Comment by synzen** [comment]
Thanks for the report, this should be fixed.
