### ISSUE TITLE
Preview show feed, but different when posted in discord.

### ISSUE THREAD

**Issue by sourcez777** [synzen/MonitoRSS#207]
**Feed URL**
https://isthereanydeal.com/rss/specials/us

**Describe the issue**
Simple feed setting showing title, description, and link.  The preview shows how it will look like, but when I click to send it to my discord to see how it looks like, the feed is different and missing information. 

**To Reproduce**
1. Go to RSS feed link I provided.
2. Click on Feed Message section.
3. Scroll down to preview of the feed.
4. See error on screenshot and the difference of how it looks on the control panel preview vs the discord bot posted feed. 

**Expected behavior**
Expect the posted feed on my discord channel to be the same as the preview in control panel. 

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/81601604/112922977-43c57000-90c2-11eb-8643-02ad8ed23d29.JPG)
![Capture2](https://user-images.githubusercontent.com/81601604/112922984-46c06080-90c2-11eb-983b-bfb2949e0a75.JPG)

**Branch (please specify one):**
Dunno, it's the one from MonitoRSS website where I invite the bot to my discord. 

If referencing the public bot, then specify public bot.

**Additional context**

**Comment by synzen** [comment]
Hi, thanks for making a report. For all issues related to the control panel, please direct them to the github repository for the control panel as instructed in the template when making a bug report:

![image](https://user-images.githubusercontent.com/18688793/131768485-81c8758b-75b5-485a-8711-fff94e718c82.png)
