### ISSUE TITLE
[Question] Edited Articles

### ISSUE THREAD

**Issue by therealgorgan** [synzen/MonitoRSS#217]
Does this have a way to re-post articles in cases where their descriptions have been edited? Sometimes we get into a situation where we have to make an alteration and end up just having to create a new article and then delete the bot's erroneous message. I thought about the Check Dates option, not sure if that would help me?

**Comment by gintil** [comment]
Apologies for the late reply - yes, you may see https://docs.monitorss.xyz/advanced-bot-customizations/np-comparisons

In your case,

```
"pcomparisons" : [
        "description"
]
```

**Comment by gintil** [comment]
Apologies for the late reply - yes, you may see https://docs.monitorss.xyz/advanced-bot-customizations/np-comparisons

In your case,
```
"pcomparisons" : [
        "description"
]
```

**Comment by synzen** [comment]
Apologies for the late reply - yes, you may see https://docs.monitorss.xyz/advanced-bot-customizations/np-comparisons

In your case,

```
"pcomparisons" : [
        "description"
]

**Comment by therealgorgan** [comment]
Thank you so much for the guidance and for the great package! ❤️
