### ISSUE TITLE
https://community.snaildos.com/latest.rss error

### ISSUE THREAD

**Issue by snaildos** [synzen/MonitoRSS#222]
## Describe the bug

Bad Cloudflare status code 503

*If this is an issue related to the public hosting bot, please use the support Discord server at https://discord.gg/pudv7Rx instead and **do not post an issue here**.*

*If this is an issue related to the control panel, please go to https://github.com/synzen/MonitoRSS-Web instead.*

## To Reproduce

RSS url is valid
Add the RSS url to the MonitoRSS bot, and it will fail.

## Expected behavior

It works.

## Screenshots
"Bad Error Code, Cloudflare error 503"

## Branch (please specify one):

public bot

**Comment by synzen** [comment]
If this is an issue related to the public hosting bot, please use the support Discord server at https://discord.gg/pudv7Rx instead and do not post an issue here.
