### ISSUE TITLE
How to deploy the bot on Railway.app

### ISSUE THREAD

**Issue by dakshy** [synzen/MonitoRSS#223]
> Heroku has dynos limit, so many devs have moved to railway.app for deploying their bots. Can you also release a guide to do the same.

> Please release guide such as blog post or youtube video, to which small devs such as me can refer to deploy the bot on Railway.

`Please` reply to my issue ASAP, and keep doing great work forever.

**Comment by tizoy12** [comment]
try replit.com

**Comment by kotx** [comment]
1. Clone repo
2. Download the Railway cli
3. `railway init`
4. Set variables as shown in #45 
5. `railway up`
6. Profit

It's not so hard.
