### ISSUE TITLE
Separate feed entries get filtered out due to common URL

### ISSUE THREAD

**Issue by rzumer** [synzen/MonitoRSS#229]
**Describe the issue**
I subscribe to some feeds that link to a common URL and even have the same title in separate entries, the description is where they can be differentiated. MonitoRSS filters most entries out because of the identical URLs. An alternate way to filter based on the full feed text or some concatenation of URL, title and description would solve this issue.

**Expected behavior**
Every new feed entry should be received and forwarded to the appropriate channel. Instead only new feed entries where the URL is different from the rest of the entries in the feed history get posted.

Since feed entries can change for whatever reason, I think this should be a per-feed option that is off by default - i.e. keep the current behavior but provide an alternative for those feeds that don't work properly without a full text comparison.

**Branch (please specify one):**
master

**Comment by synzen** [comment]
I don't think I fully understand the issue - some examples may help. But I can take a guess at a solution - would https://docs.monitorss.xyz/advanced-bot-customizations/np-comparisons help? Otherwise, please provide some more examples of your issue so that it would help me understand this better

**Comment by rzumer** [comment]
The custom comparisons seem like what I was looking for, I missed that part while browsing the guide looking for an option. I'll play with it and give more details if I can't get it to work for my use case, thanks.
