### ISSUE TITLE
Add slash commands

### ISSUE THREAD

**Issue by ririko5834** [synzen/MonitoRSS#230]
Are there any plans on updating to Discord.js v13 and adding slash commands, buttons and menus?

**Comment by synzen** [comment]
Apologies for the late reply - yes there are plans to do this since this is required by Discord by April 2022 https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Access-Deprecation-for-Verified-Bots

**Comment by synzen** [comment]
Slash commands will no longer be implemented because its capabilities are not enough for the bot (essentially decision trees are needed) - effort has now shifted to a control panel before April 2022.
