### ISSUE TITLE
[Web] Possibility to download and restore the profiles of any server/all servers

### ISSUE THREAD

**Issue by sn-o-w** [synzen/MonitoRSS#233]
**Is your feature request related to a problem? Please describe.**
Right now, you can only download just one Discord server profile into a JSON file via web UI.
Why not have the option of restoring the Discord server profile via web UI too?
And why not be able to manage easier all the servers via a single JSON file?

**Describe the solution you'd like**
Let us have the option to download/restore profiles for a single Discord server and for all Discord servers.

**Comment by synzen** [comment]
The security around having to deal with profiles is the main hurdle, and why it has never been allowed for anyone except bot owners (the people who host the bot).

Servers should not be intermingled within a single JSON file - that is not scalable.

Interfaces (control panel, bot commands, slash commands, etc.) exist for a reason, which is to strictly control who gets what data, and how data gets modified.

Unfortunately providing more granular support for editing JSON files and uploading them will not be worked on for the forseeable future given that there are more [pressing concerns](https://github.com/synzen/MonitoRSS/projects/8) at the moment
