### ISSUE TITLE
[Feature Request] Templates System

### ISSUE THREAD

**Issue by BlackYuzia** [synzen/MonitoRSS#240]
Hi there. 

This would be a short **feature request**.
I want ask about `templates` for any rss feeds.

### Feature Request

For example, I have template with name `embed`:
![image](https://user-images.githubusercontent.com/25010528/156932542-c3249e69-c260-430a-bebc-9b18d58dec21.png)

Then, I can set this template when I add feed.
Example:
```js
// [~] is my custom rss bot prefix
// ~add <url> [template]
~add rss.com/feeds embed
```

Then, I could get:
- **message body from template**
- **embed message from template**
- **filters from template**
- **subscribers from template**
- **misc options from template**

### Current Solutions

Currently, we could clone or do something like this, but, for example, in my case I have a few categorized feeds, so I should clone and edit this template by bot or web site in more cases. Also, I could forget what exactly template used in my feeds, so I could miss required template (by clone template from feed).

UPD: How I see, I already FR the same in #148 andI forget about it :eyes: But, I really hope what this feature would be added in future updates :eyes:

**Comment by synzen** [comment]
This kind of behavior should be possible now by copying settings from one connection to others with personal feeds
