### ISSUE TITLE
Thingiverse RSS feeds doesn't work

### ISSUE THREAD

**Issue by SckyzO** [synzen/MonitoRSS#258]
Hello team,

## Describe the bug

I use a selft hosted Monitor RSS, based on Dev branch, it works great, but I have one rss feed which doesnt' work with Monitor.RSS. I don't know why. I have any error in logs

This RSS :
- https://www.thingiverse.com/rss/featured
or
- https://www.thingiverse.com/rss/popular

## Screenshots

![image](https://user-images.githubusercontent.com/683678/174989251-37930cb3-8636-46b7-9e66-2abbe2ea994b.png)

## Branch (please specify one):

master or dev, same bug

Regards,

**Comment by synzen** [comment]
Apologies for the late response, are you still having this issue? If so, here are some ways to debug articles not getting delivered:

- Double check read/send message permissions/status in the control panel
- Ensure that all feed articles are publicly accessible (e.g.,not in private forums)
- Make sure your filters, if any, allow articles to come through
- Ensure the feed you're trying to add has the {date} placeholder in the test command filled out. If they don't exist, it is marked as old and won't be sent. You may bypass this by disabling date checks in the `options` command.
- If date checks are turned on (which is default), make sure articles {date} are less than a day old.
- Use the `debug` command with the feed_id (feed IDs can be acquired via the backup command) to show more verbose logs related to a particular feed, then waiting until a new article appears in the feed for it to be detected.
- Look at the delivery_records MongoDB collection if you have it set up (see the config's database section in the docs at https://docs.monitorss.xyz)
