### ISSUE TITLE
Support for Discord Forum channels

### ISSUE THREAD

**Issue by BullyPanda** [synzen/MonitoRSS#270]
This year Discord introduced [Forum channels](https://support.discord.com/hc/en-us/articles/6208479917079-Forum-Channels-FAQ) I think it would be amazing if the bot could create forum topics for selected posts.

**Comment by synzen** [comment]
I think this is a great idea - there was a previous suggestion to use threads, but since Discord has introduced forums, I believe forums may be better. It's now a card on the [roadmap](https://github.com/synzen/MonitoRSS/projects/8)

**Comment by LEv145** [comment]
I tried to implement this a little bit: https://github.com/LEv145/MonitoRSS-API

**Comment by xan2622** [comment]
I second this request for _forum-channels_ but also for _threads_.

**Comment by JamesDAdams** [comment]
News ?

**Comment by synzen** [comment]
Support should be added now for personal feeds, for both threads and forums
