### ISSUE TITLE
New era of discord apps, discord api has changed

### ISSUE THREAD

**Issue by FriendlyUser** [synzen/MonitoRSS#275]
## Describe the bug

https://discord.com/blog/welcome-to-the-new-era-of-discord-apps

Seems like my discord rss bot isnt working anymore, also monitorrss isnt working for me either

*If this is an issue related to the public hosting bot, please use the support Discord server at https://discord.gg/pudv7Rx instead and **do not post an issue here**.*

*If this is an issue related to the control panel, please go to https://github.com/synzen/MonitoRSS-Web instead.*

## To Reproduce

1. attempt rss.add or rss.help

no response from bot

## Expected behavior

bot sends a message

## Screenshots

![image](https://user-images.githubusercontent.com/13860264/189461282-2c04ad95-1c70-47de-a9d1-ef7133e2a8de.png)

feeds.add is for my personal monitorrss bot

## Branch (please specify one):

master, dev, or public bot

## Additional context

https://discord.com/blog/welcome-to-the-new-era-of-discord-apps

Please let me know if this is a me problem.

**Comment by synzen** [comment]
Thanks for the report. Please be sure that Message Content Intent is enabled for your personal bot:

![image](https://user-images.githubusercontent.com/18688793/189461786-3800fe91-f07c-4bd0-9fef-a01f57801749.png)

This is a required change as of September - for more information, you may see https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ

Commands have been disabled on the public bot as a result of Discord's breaking change, and the bot will eventually only support a web interface for interactions.

**Comment by FriendlyUser** [comment]
Also do the command prefix have to start with / now?


```
DRSS_BOT_PREFIX=/feeds
```

**Comment by synzen** [comment]
There is no slash command support so the prefix/commands will work the same way as before

**Comment by FriendlyUser** [comment]
Okay, think it just took a day or a couple hours for the settings to propagate.

**Comment by synzen** [comment]
Glad to hear.

**Comment by HackerDaGreat57** [comment]
THIS ISSUE SHOULD BE PINNED. PLEASE. The comment about enabling Content Intent saved me from a headache.
