### ISSUE TITLE
Some symblos instead of Text in Russian

### ISSUE THREAD

**Issue by masterwishx** [synzen/MonitoRSS#285]
Having some symbols in one site instead of text : 
but other sites is OK
![image](https://user-images.githubusercontent.com/28630321/199201987-8ac15928-878c-4caf-a0cc-c5d9f5872ace.png)

**Comment by masterwishx** [comment]
http://rustorka.com/forum/rssd.xml

**Comment by synzen** [comment]
If this is still an issue, please feel free to re-open this issue.

On self-hosted instances. they must be added to the `config.feeds.decode` config option.

On the public bot, at this time I must manually handle each feed when they have special characters.

**Comment by masterwishx** [comment]
can you explain where i find this config option ?

**Comment by masterwishx** [comment]
i shold use only in Bot ot in Web also ?
DRSS_FEEDS_DECODE can be used ?

DRSS_FEEDS_DECODE= {link} utf8   ?

they not utf8 by default ?
