### ISSUE TITLE
404 code on my local FreshRSS address when trying to add link

### ISSUE THREAD

**Issue by masterwishx** [synzen/MonitoRSS#286]
Tryed to add link from my FreshRSS at address :
http://192.168.0.199:8181/i/?a=rss&get=f_10&rid=636xxxxx25f&hours=168

but having error 
![image](https://user-images.githubusercontent.com/28630321/199234264-4a023414-59a7-42b9-b056-d77bdf3586c5.png)

is it possible to add it at all ?

Using last version of docker in Unraid

**Comment by synzen** [comment]
If this is still an issue, please feel free to re-open the issue.

That URL is a private IP address on your local network - it is unreachable from outside your network without more complex network configurations.
