### ISSUE TITLE
A russian symbols can't display

### ISSUE THREAD

**Issue by FastBoot-pixellab** [synzen/MonitoRSS#326]
## Describe the bug

Sorry about public bot here. But i not have phone number on discord :|
But russian symbold changes to �

## To Reproduce

1. I will subscibe to opennet.ru
2. result

## Branch (please specify one):

public bot

## Screenshots
![Screenshot_20230304_105102](https://user-images.githubusercontent.com/59791772/222883975-40c7f3ef-f483-4452-8162-fe20bbc4050e.png)

**Comment by simonenkoilya** [comment]
How did you decide that?
