### ISSUE TITLE
Redundant leading space in lists

### ISSUE THREAD

**Issue by m417z** [synzen/MonitoRSS#327]
## Describe the bug

First of all, thank you for the great project and service. I needed a simple update service for my Discord channel and MonitoRSS is just perfect for that.

A minor bug report: Lists have an extra leading space for each bullet but the first, which looks unaligned and wrong.

Source HTML:

```html
<ul>
<li>Renamed from "Large Taskbar Icons" to "Taskbar height and icon size".</li>
<li>Fixed support for secondary taskbars.</li>
<!-- ... -->
</ul>
```

Result:

![image](https://user-images.githubusercontent.com/4129781/226104691-b009f3bb-c0dd-4b76-bcd0-b3c45cee4ea8.png)

## To Reproduce

Use an RSS feed with a list.
My feed for reference: https://mods.windhawk.net/updates.atom

## Expected behavior

Be consistent. Batter have no leading spaces at all in my opinion.

## Screenshots

See above.

## Branch (please specify one):

public bot

## Additional context

I tried looking at the code, I found that [node-html-to-text](https://github.com/html-to-text/node-html-to-text) is used, and it has the following formetter option:

[`itemPrefix` with default value `' * '`](https://github.com/html-to-text/node-html-to-text/blob/5c7a2b2b66d5eea7c1e5b6cd80c5e2d17e119912/packages/html-to-text/README.md?plain=1#L237)

I believe that setting it to `'* '` should fix the problem. I'm not familiar with the project so I'm not sure what's the best place for it, I saw multiple places that use `node-html-to-text`, but I believe that it should be an easy fix.

**Edit:** Even better, how about setting it to `'• '`?
Looks much better in my opinion:

![image](https://user-images.githubusercontent.com/4129781/226109278-2b441c67-61af-45e2-8064-3fc1821efaed.png)

**Comment by synzen** [comment]
Apologies for the late reply. Since you're on the personal bot, is it reasonable for you to move over to personal feeds (accessible at https://my.monitorss.xyz)? I believe this should not be an issue there.

**Comment by m417z** [comment]
I tried configuring the personal feeds. That didn't work for me - the dialog for adding a new connection doesn't list all channels, specifically the announcement channels that I want the news to be posted on. Is it a known limitation?

**Comment by synzen** [comment]
I see - no, that was an oversight. Announcement channels should now be available

Note however that auto-publishing them is not currently supported, but a separate bot to auto-publish messages might be a solution.

**Comment by m417z** [comment]
Thanks, I could set it up now.

Some feedback:

* I didn't find a way to disable the legacy feeds. I prefer not to remove them yet to be able to go back if anything goes wrong.
* I didn't find a preview option in the personal feeds UI, which requires sending a test message to the channel to see the formatting result.
* Adding a Discord channel connection - I think it makes sense to make the custom name optional, and to just show the server and channel names if not set.

But the above can be worked around and isn't very important.

Regarding the issue itself - the inconsistent leading spaces are fixed, see screenshot below. But still, I think that replacing `' * '` with `'• '` would result in a cleaner output. What do you think?

![image](https://user-images.githubusercontent.com/4129781/230735331-84c139f6-5ad5-4aca-bf3a-189690be8721.png)

**Comment by synzen** [comment]
Yes I think that would be good as well. Thanks for the feedback.

- The preview section has been missing/planned for a while, but it should be available now.
- The name for the connection should auto-populate as soon as you select a channel
- The bullet point character has also been updated as requested

I believe this issue is resolved now, but you may let me know if you have any more concerns or suggestions

**Comment by m417z** [comment]
@synzen Recently, Discord added support for markdown lists, so you might want to revert that change.
https://twitter.com/discord/status/1648377300776370205
