### ISSUE TITLE
Importing backup in a Docker container

### ISSUE THREAD

**Issue by lexisother** [synzen/MonitoRSS#328]
First of all, I apologize for using the issue tracker as a support hotline, but the Discord server requires me to add my phone number to my account which I do not want to do.

Now; for my issue. I have made a backup of the settings using `rss.backup`, and it is mentioned on the web dashboard that these backups can be restored through manual intervention.

However, I am running the bot through Docker Compose, and I have no idea how to restore my backup to a new instance. The documentation does not mention this, unless I am glancing over it. Any ideas?

**Comment by synzen** [comment]
Hi, since you are self-hosting, you may restore it using the `restore` Bot Owner discord command: https://docs.monitorss.xyz/configuration/discord-commands

**Comment by lexisother** [comment]
Ah, I had completely skipped that page. Apologies for asking a stupid question, and thanks for the swift reply!
