### ISSUE TITLE
A way to shorten values

### ISSUE THREAD

**Issue by dt192** [synzen/MonitoRSS#330]
It would be good if there were some options to shorten values, as description for example can be quite long.

It would be nice to have some options such as max length (in chars) and maybe a regex option to split at. This sort of thing maybe `{{description}, maxLength:250}` or `{{description}, split:/^(.*)\n{2}/s}`

You currently have the `Split Content` option, but that only splits the whole message when it's longer than discord's limit, so is not helpful for this.

**Comment by synzen** [comment]
Placeholder limits should now be implemented for personal feeds on the public bot. If you are inquiring about legacy feeds however, feature development on them has stopped in favor of the transition to personal feeds. For more information on the transition, please see the news channel in the Discord support server: https://discord.gg/kRjevzXhss

Feel free to reply if you have any more questions

**Comment by dt192** [comment]
@synzen Thanks, that's a nice implementation.

It does appear to have a bug though (or I'm doing it wrong)

This is with a limit of 250 with `...` appended
![2023-07-17_16-08](https://github.com/synzen/MonitoRSS/assets/2612048/978897c6-3c33-4e50-805d-8307949be3dd)

This is with a limit of 275 with `...` appended, Same with 300. I'm expecting to see more text not less.
![2023-07-17_16-09](https://github.com/synzen/MonitoRSS/assets/2612048/7c68a0a3-98dd-44d6-8b2c-4ce0961b15d4)

These screenshots are just from the preview, so might be working fine live, I'd need to wait for a post to find out.

**Comment by synzen** [comment]
Unfortunately, a slightly larger limit does not necessarily mean more characters will be included. It will depend on a number of factors like how many new lines there are, what punctuation it sees, and how long each "part" is after it splits on the aforementioned factors. You may have to steadily increase the limit until it looks satisfactory

But I've slightly adjusted the splitting to take into account more punctuation like `?` and `!` - please try again now to see if it satisfies your requirements

For the record, you may also send it directly to Discord using the Send Article button found on any given connection page:

![image](https://github.com/synzen/MonitoRSS/assets/18688793/8df9f22b-0afa-42cb-9aeb-a3edf335a588)

to see the actual message (text splitting/limits should be 100% accurate - it's Discord-specific message formatting that are sometimes inaccurate)
