### ISSUE TITLE
Excess newline due to formatting

### ISSUE THREAD

**Issue by m417z** [synzen/MonitoRSS#343]
## Describe the bug

An excess newline is added in some cases.

For example, feed content:

```html
<p><strong>Before</strong>:</p>
<p><img src="https://raw.githubusercontent.com/...png" alt="Before" /></p>
<p><strong>After</strong>:</p>
<p><img src="https://raw.githubusercontent.com/...png" alt="After" /></p>
```

Result:

![image](https://github.com/synzen/MonitoRSS/assets/4129781/ef27a311-b904-49b0-9626-d8f41828839c)

## To Reproduce

1. Have a feed with content similar to the above
2. Observe that an unnecessary newline is added

## Branch (please specify one):

public bot

**Comment by synzen** [comment]
Just to be abundantly clear on expectations, what is the exact output that you're looking for in this case?

**Comment by m417z** [comment]
I expect this:
`<p><strong>Before</strong>:</p>`

To become:
<p><strong>Before</strong>:</p>

And not:
<p><strong>Before</strong><br>
:</p>

**Comment by synzen** [comment]
Thanks for clarifying. I believe this should now be fixed in https://github.com/synzen/MonitoRSS/commit/ffa503c5eb879607ea338b4217a273b9727e2241
