### ISSUE TITLE
I need help getting verified on the Discord server, and can't contact you anywhere else

### ISSUE THREAD

**Issue by LegoLoco7** [synzen/MonitoRSS#347]
I'm sorry for putting this here, but I can't contact you on Discord at all unless I send you a friend request, which I fear you wouldn't accept. I don't have a phone number, so I can't verify my account on the server. I _am_ verified via email, if that helps. Just not via phone number, which the server seems to require. I need help with converting my legacy feeds to personal feeds, and a couple of other things.

**Comment by synzen** [comment]
Hi, the verification level on the server has been decreased now.

You may feel free to continue clarifying your request for help here, create a ticket via the "Help" button at the bottom right of https://monitorss.xyz/ or at https://support.monitorss.xyz, or continue the conversion in Discord https://discord.gg/pudv7Rx

**Comment by LegoLoco7** [comment]
Okay, thanks. It wasn't very clear that those methods existed, because the main website and the control panel promote the Discord server a lot when talking about support-related things.
