### ISSUE TITLE
Add support for code in markdown

### ISSUE THREAD

**Issue by m417z** [synzen/MonitoRSS#356]
**Is your feature request related to a problem? Please describe.**
Looks like bold, italic, and underline styles are supported, but not code.

**Describe the solution you'd like**
Given content such as the following in the feed:
```html
Some <code>code</code> right here
```
I'd like to get:
```markdown
Some `code` right here
```

**Additional context**
I assume it has to be added somewhere around here:
https://github.com/search?q=repo%3Asynzen%2FMonitoRSS+Bolded+markdown&type=code

There are four similar blocks of html to markdown handling. I'm not sure whether they all need to change.

**Comment by synzen** [comment]
Thanks for the report. This should be fixed now in https://github.com/synzen/MonitoRSS/commit/dea3a70380c2f3115686104a7800b2b181733415 (the code search you linked were all related to legacy code that's no longer used now)
