### ISSUE TITLE
Codebase is unlicensed

### ISSUE THREAD

**Issue by marceline-cramer** [synzen/MonitoRSS#357]
## Describe the bug

This codebase does not have any kind of software license and is therefore All Rights Reserved to the authors.

## To Reproduce

Look at the codebase. Notice the lack of licensing.

## Expected behavior

The codebase should be licensed under a specific free software license, such as MIT, Apache, BSD, or anything else, and include a copy of that license in the source tree that GitHub can detect and display on the repository.

## Screenshots

N/A

## Branch (please specify one):

N/A

## Additional context

A lot of developers feel a lot more comfortable when the code they are either using over the internet or self-hosting explicitly declares the rights and terms granted to them by the software. It's really awesome that the core MonitoRSS code is source-open but it would mean a lot if it could go the rest of the way to being open-source by licensing the code under a proper license like the MonitoRSS-Clone repo does.

**Comment by synzen** [comment]
Thanks for bringing this to my attention - the MIT license should be restored on the main branch now
