### ISSUE TITLE
[FR] Improvements

### ISSUE THREAD

**Issue by BlackYuzia** [synzen/MonitoRSS#358]
I've decided to analyze which specific features are missing in the new version of the application. I hope this will make it more convenient for everyone.

### Problem

In the old version, it was inconvenient that you couldn't directly navigate to a page with an RSS feed. All navigations were done through JS. In the new version, this issue has been addressed (now we have /feeds/:hash, etc.). However, this is only a partial fix because the buttons with feeds are not links. We cannot open them in a new window/tab.
So, if we want to open and modify several feeds, we will need to go into each one. Additionally, when returning, the page state will be reset (which could be saved but is not currently implemented). Therefore, any feed search will be reset (for example, if you were looking for all news feeds, after returning, you would have to enter the query again).

### Solution

My suggestion is as follows: make all navigation elements (those that lead us/you through a link or change/overwrite it without refreshing the page) actual hyperlinks. Instead of navigating through JS, create “real” navigation as on any regular website. This will improve the user experience, site convenience, efficiency, and the speed of feed modification. It will also allow for the simultaneous modification of multiple feeds, rather than one by one.

### Additional

In most cases, you want the navigation to the feeds to be links. This will be sufficient for the majority of users.
![image](https://github.com/synzen/MonitoRSS/assets/25010528/cb031871-78b4-4c7e-8530-38e26d6eefd0)

Certainly, you can implement this for any other navigation buttons as well. However, it may not be as crucial for those cases.
![image](https://github.com/synzen/MonitoRSS/assets/25010528/62ccba13-694d-40bf-a926-10e2f5d4e7b1)

### Problem

This is less critical than the previous point, but as a small improvement, it's still a compelling argument. So, we see the name of the Discord channel to which messages will be sent (img 1). However, we need to manually search for the server and channel on the server (or immediately by channel name, but this doesn't guarantee uniqueness). This is unnecessary time that we can save for the user.

### Solution

The suggestion is as follows: Add link in channel name (img 1) to the Discord server + Discord channel for quick access to this channel `https://canary.discord.com/channels/:serverId/:channelId`

### Additional

![image](https://github.com/synzen/MonitoRSS/assets/25010528/e58c3ed6-e5de-41eb-a579-eac9215a7d1e)

### Problem

After using the website for a few hours, I want to add that two functions are very necessary. The first one is channel updates.

Sometimes, it's necessary to refresh the page because the list of channels doesn't include a newly created channel. Perhaps, it's necessary to simply subscribe the bot to all channel changes on the server.

### Additional

![image](https://github.com/synzen/MonitoRSS/assets/25010528/dd9d45d2-ee13-4df3-a6fd-9511135f114f)

### Problem

The second important function is the creation of channels (from the same menu? see the image below) and categories. I discussed this in more detail in topic #336. I believe it's already planned. So, we're waiting for it..

### Additional

![image](https://github.com/synzen/MonitoRSS/assets/25010528/bfbe374d-9cf8-4c92-88f6-ccc27778b695)

### Problem

When you go to your feeds (/feeds) and then perform actions like searching for RSS feeds, clicking on a feed, and then going back, the state resets. In other words, you have to redo the search/filter for feeds to find the next one you need.

I think this inconvenience could be addressed by preserving the search page state after navigating to another page and returning back.

**So far, that's all. Thank you for your attention.**

**Comment by synzen** [comment]
Hi, thanks for taking the time to provide such detailed feedback.

1. I agree. I've pushed an update to main that makes the title links so that you may click and open it within a new tab if desired.
2. I agree this would be an improvement - this should be available on the main branch now.
3/4. While I agree it is a nuisance to refresh, the complexity of implementing this (versus the benefits received) has unfortunately pushed this to be lower priority. However, I've added it to https://github.com/synzen/MonitoRSS/projects/8#card-91171272 to be tracked
5. I agree - this should be available on the main branch now.
