### ISSUE TITLE
html to markdown: `<pre><code>`

### ISSUE THREAD

**Issue by m417z** [synzen/MonitoRSS#373]
**Feed URL**
https://mods.windhawk.net/updates.atom

**Describe the issue**
I have a feed item with the following HTML content:
```html
<pre><code>sfc /scanfile=c:\windows\system32\shellstyle.dll</code></pre>
```

`<pre><code>` [is recommended for code blocks](https://stackoverflow.com/a/4611735).

This results in the following markdown:

    ````sfc /scanfile=c:\windows\system32\shellstyle.dll````

And in turn, in a slightly broken post:
![image](https://github.com/synzen/MonitoRSS/assets/4129781/e1e0db37-702d-40f7-8a45-bd81d2994e36)

**Expected behavior**
Have three, not four backticks in the resulting markdown.

**Screenshots**
See above.

**Branch (please specify one):**
public bot

If referencing the public bot, then specify public bot.

**Comment by synzen** [comment]
Thanks for the report - this should be updated to have the expected behavior in https://github.com/synzen/MonitoRSS/commit/3182972dd9a7edb2278a9798edaec02490fd1286, and is currently in the process of being deployed (give or take ~15 minutes). Feel free to re-open if you continue to face issues.
