### ISSUE TITLE
No discord messages after MongoDB is restarted

### ISSUE THREAD

**Issue by masterwishx** [synzen/MonitoRSS#375]
Using selfhosted docker MonitoRSS bot + WebUi in Unraid. 

All working fine but when MongoDB is updated and restarted bot reconnect and all working fine but no messages sending to discord until restart MonitoRSS bot + Webui. 

Can it be fixed?

**Comment by synzen** [comment]
Thanks for the report. I've pushed an [update](https://github.com/synzen/MonitoRSS/commit/fb249247bd5efbf2c6bdf16ee2a63cc9c5358ff4) now that will cause the container responsible for sending messages will automatically exit if it detects its MongoDB connection is faulty. This should allow any auto-restart policies to automatically restart it in that case. Feel free to re-open if you continue to face issues.

**Comment by masterwishx** [comment]
> Thanks for the report. I've pushed an [update](https://github.com/synzen/MonitoRSS/commit/fb249247bd5efbf2c6bdf16ee2a63cc9c5358ff4) now that will cause the container responsible for sending messages will automatically exit if it detects its MongoDB connection is faulty. This should allow any auto-restart policies to automatically restart it in that case. Feel free to re-open if you continue to face issues.

Thanks im using old config for selfhosted and container from dockerhub 1 year old not sure how to update container ....

**Comment by synzen** [comment]
Please see https://github.com/synzen/MonitoRSS/projects/8#card-92704500 in that case for updating to the new set up

**Comment by masterwishx** [comment]
> that case for updating to the new set up

in home Unraid server im using docker not docker compose, as you dont have already builded image for new version , i think i should move MonitoRSS to vps with docker compose and build it there ...
