### ISSUE TITLE
Feed is not recognized, but the feed itself is valid

### ISSUE THREAD

**Issue by FeikoJoosten** [synzen/MonitoRSS#380]
**Feed URL**
https://nitter.poast.org/GuildWars2/rss

**Describe the issue**
I'm trying to use the feed above, but when saving the feed it states it cannot verify the feed. (See image below)
However, when verifying the feed with third party rss validators, they all state the feed is correct.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnitter.poast.org%2FGuildWars2%2Frss
https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fnitter.poast.org%2FGuildWars2%2Frss
https://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fnitter.poast.org%2FGuildWars2%2Frss

**To Reproduce**
1. Go to https://my.monitorss.xyz/feeds
2. Click on `Add a new feed`
3. Paste the given rss url and add a title
4. Click save
5. See error

**Expected behavior**
I would expect the rss feed to be added

**Screenshots**
![image](https://github.com/user-attachments/assets/e519f306-d4c7-47d8-a57b-b57929628674)

**Branch (please specify one):**
N/A

If referencing the public bot, then specify public bot.

**Additional context**
N/A

**Comment by synzen** [comment]
Thanks for the details. Do you happen to be in control of the feed? 

```
curl: (7) Failed to connect to nitter.poast.org port 443 after 43 ms: Couldn't connect to server

**Comment by FeikoJoosten** [comment]
Unfortunately I’m not in control of the feed. I do agree, it’s quite likely that’s the issue. If so, maybe the error should indicate this?

**Comment by synzen** [comment]
Agreed in that the error should represent that - this is fixed now in https://github.com/synzen/MonitoRSS/commit/de9f9f3a3b06bd2d9322a706803636ee79fe5ab6 where it will say the request failed rather than an invalid feed

Unfortunately I don't think I can do much more than this besides suggesting that you may a different feed/host for similar content (or self-hosting, if it works on your network)

**Comment by FeikoJoosten** [comment]
Thanks for the error improvement and np, I’ll see if I can contact the host!
