### ISSUE TITLE
Cannot install fresh

### ISSUE THREAD

**Issue by slord399** [synzen/MonitoRSS#381]
## Describe the bug

When trying to deploy as per as instruction regarding self-host, it simply failed to start some docker container.

## To Reproduce

1. Try to build on Ubuntu 24.04.
2. Follow instruction to build.
3. Check docker running status.
4. Few container failed to run or stated unhealthy.

## Expected behavior

All container installed up and running normally.
(which makes web panel accesible also)

## Screenshots

As it failed on build stage, I don't think it help much but if you need one, let me know.

## Branch (please specify one):

main

## Additional context

Seems to be some yml be outdated so I'm suspecting around there.
(which include outdated version string in cludeed there too)

If need to use older ubuntu to install, maybe good idea to state it on readme.

**Comment by synzen** [comment]
Hi, I'm confused here since you're stating 

> Few container failed to run or stated unhealthy.

but then you said 

> it failed on build stage

which seems to imply that it never got past the build stage so it was never able to run/start in the first place. Can you please provide some text or screenshots the specific error/issues you're facing?

**Comment by slord399** [comment]
![image](https://github.com/user-attachments/assets/bc9eb06f-f419-443f-bb35-d22d47440c52)
At 1st run, "rabbitmq-broker" got failed most of case.
(it can be resolve by running docker composr once again)

As shown on screenshot, only half of docker container comes up and running. some even exist after initializing process.

1 things to note is, there are more than 10 lines of deprecated warning while build process going on, which doesn't prevent build process but bring up concern of incompatibility issue.

If you point me what section you need more info on, I shall provide it.

**Comment by synzen** [comment]
Thanks for the details. It is currently expected that you may sometimes have to either restart some containers if they initially fail to start - the only containers that don't need to be running are the ones ending in `-migration`

The `rabbitmq` container is the one that most other containers depend on, and you _should_ be able to just restart it for it to run. If it repeatedly fails to start after repeated attempts to reboot it, please provide the logs for that container: `docker logs rabbitmq-broker --tail 50`. Once that is running, you can try individually restarting the other containers
